---
# Installs Docker on a host
- name: Uninstalling old or default Docker versions
  apt:
    name: [docker,docker-engine,docker.io,ontainerd,runc]
    state: absent

- name: Installing Docker dependencies
  apt:
    name: [apt-transport-https,ca-certificates,curl,gnupg-agent,software-properties-common]
    state: present

- name: Add Docker's GPG Key
  become: yes
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present 

- name: Get distro codename
  command: echo $(lsb_release -cs)
  register: command_output

- name: Add Docker repository
  become: yes
  shell: > 
    add-apt-repository 
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu 
    {{ command_output.stdout }} 
    stable"

- name: Updating apt cache (again)
  apt:
    update_cache: yes

- name: Installing Docker CE
  apt:
    name: [docker-ce, docker-ce-cli, containerd.io]
    state: present

- name: Uninstall current version of the Python Docker Module 
  pip:
    name: [docker, docker-py, docker-compose]
    state: absent

- name: Install old version of Docker Compose
  pip:
    name: docker-compose==1.9.0
